export const DEMO_TASKS = [
  {
    id: 1,
    title: 'Нарисовать логотип для телеграм-бота',
    description: 'Нужен минималистичный логотип в стиле flat-design. Исходники в SVG обязательны. Цветовая схема — фиолетово-белая.',
    reward: 150,
    status: 'OPEN' as const,
    category: 'design',
    tags: ['логотип', 'svg', 'flat'],
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    posterId: 2,
    executorId: null,
    poster: { id: 2, firstName: 'Алексей', username: 'alex_dev' },
  },
  {
    id: 2,
    title: 'Перевести landing page с английского на русский',
    description: 'Около 800 слов. Нужен живой, маркетинговый перевод — не машинный. Тематика: SaaS-продукт для команд.',
    reward: 80,
    status: 'OPEN' as const,
    category: 'translation',
    tags: ['перевод', 'landing', 'EN→RU'],
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    posterId: 3,
    executorId: null,
    poster: { id: 3, firstName: 'Марина', username: 'marina_k' },
  },
  {
    id: 3,
    title: 'Настроить CI/CD pipeline на GitHub Actions',
    description: 'Node.js проект. Нужны джобы: lint, test, build, deploy на Railway. Секреты уже настроены, нужна только конфигурация.',
    reward: 200,
    status: 'IN_PROGRESS' as const,
    category: 'development',
    tags: ['devops', 'github-actions', 'node'],
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    posterId: 4,
    executorId: 1,
    poster: { id: 4, firstName: 'Дмитрий', username: null },
  },
  {
    id: 4,
    title: 'Написать 5 постов для Telegram-канала о криптовалютах',
    description: 'Каждый пост 300–500 символов. Тон: нейтральный, информационный. Темы дам отдельно после взятия задачи.',
    reward: 120,
    status: 'OPEN' as const,
    category: 'writing',
    tags: ['тексты', 'telegram', 'крипто'],
    deadline: null,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    posterId: 5,
    executorId: null,
    poster: { id: 5, firstName: 'Олег', username: 'oleg_crypto' },
  },
  {
    id: 5,
    title: 'Собрать данные конкурентов: цены и фичи (10 сайтов)',
    description: 'Нужна таблица Google Sheets с ценами, тарифами и ключевыми фичами 10 SaaS-конкурентов в нише task management.',
    reward: 90,
    status: 'OPEN' as const,
    category: 'data',
    tags: ['research', 'excel', 'конкуренты'],
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    posterId: 2,
    executorId: null,
    poster: { id: 2, firstName: 'Алексей', username: 'alex_dev' },
  },
  {
    id: 6,
    title: 'Сверстать email-шаблон (responsive)',
    description: 'Дизайн в Figma уже готов. Нужна HTML-вёрстка совместимая с Gmail, Outlook, Apple Mail. Ширина 600px.',
    reward: 110,
    status: 'REVIEW' as const,
    category: 'development',
    tags: ['html', 'email', 'верстка'],
    deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    posterId: 6,
    executorId: 1,
    poster: { id: 6, firstName: 'Светлана', username: 'sv_design' },
  },
]

export const DEMO_USER = {
  id: 1,
  firstName: 'Иван',
  lastName: 'Петров',
  username: 'ivan_p',
  photoUrl: null,
  coins: 580,
  isAdmin: false,
}
